### ISSUE TITLE
Theme no longer working after install : Unknown "extends" tag

### ISSUE THREAD

**Issue by flyke** [djboris88/timber-commented-include#1]
After I install this with:
`composer require djboris88/timber-commented-include --dev`
My theme no longer works, and I get these errors:
` Fatal error: Uncaught Twig_Error_Syntax: Unknown "extends" tag. Did you mean "extends"? in ...\wp-content\themes\mytheme\templates\wordpress\page.twig on line 1`
`Twig_Error_Syntax: Unknown "extends" tag. Did you mean "extends"? in ...\wp-content\themes\mytheme\templates\wordpress\page.twig on line 1`

**Comment by djboris88** [comment]
I have tested it with multiple nested extended templates and it is working well for me. Can you please paste that first line of `page.twig` file?

Also, what versions of Timber are you using, and how is it installed, as a WP plugin or with Composer?

**Comment by herrschuessler** [comment]
I ran into a similar problem when I had the plugin WPML installed and active. WPML includes its own Twig version which also creates problems when installing Timber via composer, not as plugin.

**Comment by djboris88** [comment]
Should be solved by the latest pull request.
