### ISSUE TITLE
Outdated dependency

### ISSUE THREAD

**Issue by graham73may** [djboris88/timber-commented-include#3]
Please can you update the composer json to require your latest twig-commented-include release?

I believe this line:
https://github.com/djboris88/timber-commented-include/blob/master/composer.json#L24C2-L24C45

Needs updating to:
```
	"djboris88/twig-commented-include": "^2.0"
```

Related: https://github.com/djboris88/twig-commented-include/pull/1

**Comment by graham73may** [comment]
Created a PR for this
https://github.com/djboris88/timber-commented-include/pull/4

@djboris88 Hopefully it's a simple one to merge soon :)

**Comment by frederikkempe** [comment]
@djboris88 can you look into @graham73may PR? :)

**Comment by frederikkempe** [comment]
@djboris88 Any chance you can have a look at this? Thanks in advance!

**Comment by djboris88** [comment]
PR is merged. Thank you @graham73may and @frederikkempe, and sorry for waitthe 

.

**Comment by djboris88** [comment]
PR is merged. Thank you @graham73may and @frederikkempe, and sorry for the delay.

**Comment by graham73may** [comment]
Thanks for merging @djboris88, could you trigger a new release please?
